### ISSUE TITLE
Loss of default colors when adding a theme

### ISSUE THREAD

**Issue by jasonblalock** [jxnblk/rebass#284]
Upgraded from 1.0.0-2 to 1.0.3 and the default colors are not rendering anymore when I provide a theme. I'm not sure if maybe the process for theming changed and I missed it, but without the theme it works fine.

I've been able to reproduce it in your storybook by replacing the code for the slider:
```js
<Provider theme={{
	colors: {
    darkgray: '#686868',
    lightgray:'#b3b3b3',
    medgray: '#828282',
    teal: '#00d6b1',
    white: '#fff'
  }
}}>
	<Slider />
</Provider>
```

The CSS styling for the slider element produced:

```css
.dgrMaL {
    display: block;
    height: 4px;
    cursor: pointer;
    color: inherit;
    border-radius: 99999px;
    background-color: gray2;       # This being the problematic attribute
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
}
```
