### ISSUE TITLE
Unknown 'gray2' in multiple components

### ISSUE THREAD

**Issue by selrond** [jxnblk/rebass#322]
I've noticed there's invalid color `gray2` set on [multiple components](https://github.com/jxnblk/rebass/blob/master/src/components.js) (Input, Select, Textarea, Slider, Border, Card, Progress, Tabs) `background-color`s and `box shadow`s set by default.  Thus the intended properties don't render.

A sample code from my page:
```css
.iUtigF {
	font-family: inherit;
	line-height: inherit;
	display: inline-block;
	vertical-align: middle;
	border: 0;
	box-shadow: inset 0 0 0 1px gray2;
	border-radius: 25px;
	-webkit-appearance: none;
	-moz-appearance: none;
	appearance: none;
	text-align: center;
	font-weight: 400;
}
```
